AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*"
Metrics/LineLength:
  Max: 100
Metrics/ParameterLists:
  Max: 3
Style/AndOr:
  EnforcedStyle: conditionals
Style/AutoResourceCleanup:
  Enabled: true
Style/CaseIndentation:
  IndentOneStep: true
Style/CollectionMethods:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FirstArrayElementLineBreak:
  Enabled: true
Style/FirstHashElementLineBreak:
  Enabled: true
Style/FirstMethodArgumentLineBreak:
  Enabled: true
Style/FirstMethodParameterLineBreak:
  Enabled: true
Style/ImplicitRuntimeError:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/MissingElse:
  Enabled: true
Style/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line
Style/NumericLiterals:
  Enabled: false
Style/OptionHash:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/SafeNavigation:
  Enabled: false
Style/Send:
  Enabled: true
Style/SignalException:
  EnforcedStyle: semantic
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/StringMethods:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/VariableNumber:
  EnforcedStyle: snake_case
